[package]
name = "SE"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boolector = "0.4.2"
llvm-ir = {path = "../../llvm-ir"}
haybale = {path = "../../Haybale",features = ["llvm-9"]}